### ISSUE TITLE
大侠，有些墙外网站无法访问怎么解决？

### ISSUE THREAD

**Issue by lanner2000** [MuJJus/vpnd-openwrt#11]
大侠，新年快乐！
一直用您的VPND，非常好用，速度也很快，看youtube我的100M光纤基本可以跑满！昨天打算试试instagram，但发现instagram无法访问，直接电脑连VPN可以访问，用SS可以访问，但用VPND就不行，看了您的通行列表ipset.conf，instagram在里面，但就是打不开网站，请问我该如何操作呢！谢谢！
2015.2.20

**Comment by lanner2000** [comment]
另外还有个问题，关闭VPND是不是在VPND里面的启用选项取消就行了，接口里要关闭吗？透明代理的选项需要勾选吗，有什么用处呢？谢谢!

**Comment by cqhtyi** [comment]
新年快乐！
1.建议使用MTR工具追一下instagram.com，确认一下是哪个环节出了问题。
2.是的，关闭“启用选项”即可。接口随便关不关都行。
3.VPND是一个分流工具，而不是翻墙工具。“透明代理”需要和ShadowSocks，GoAgent等工具配合使用。没有写WIKI，原理什么的，翻翻源码吧。

**Comment by lanner2000** [comment]
非常感谢您新年还及时回复我的疑问，我只是个初学者，代码也还是看得云里雾里。
我用WINMTR追了下，数据确实进了VPN，但到了一个美国节点就没了
instagram.com
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                             OpenWrt.lan -    0 |    7 |    7 |    0 |    0 |    1 |    0 |
|                            192.168.99.1 -    0 |    7 |    7 |  162 |  164 |  166 |  165 |
|                           v33.sioru.com -    0 |    7 |    7 |  162 |  164 |  166 |  166 |
|                  v213.core1.phx2.he.net -    0 |    7 |    7 |  170 |  178 |  182 |  179 |
|              10ge15-3.core1.dal1.he.net -    0 |    7 |    7 |  183 |  184 |  186 |  186 |
|               equinix01-dfw3.amazon.com -    0 |    7 |    7 |  188 |  199 |  227 |  194 |
|                           54.240.229.94 -    0 |    7 |    7 |  224 |  226 |  228 |  224 |
|                            54.240.229.4 -    0 |    7 |    7 |  222 |  223 |  226 |  224 |
|                          54.240.229.162 -    0 |    7 |    7 |  222 |  223 |  226 |  224 |
|                          54.240.229.123 -    0 |    7 |    7 |  221 |  226 |  229 |  225 |
|                          205.251.244.18 -    0 |    7 |    7 |  226 |  228 |  230 |  230 |
|                            72.21.220.55 -    0 |    7 |    7 |  222 |  224 |  226 |  222 |
|                         205.251.245.234 -    0 |    7 |    7 |  218 |  219 |  221 |  220 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    1 |    0 |    0 |    0 |    0 |    0 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider
，我应该怎么做？
还有关于您说的“透明代理”需要和SHADOWSOCKS配合使用的问题：我理解shadowsocks+chinadns不是就能翻墙了吗，它和VPN不是同样功能的两个工具吗，怎么理解配合使用呢，谢谢！

**Comment by lanner2000** [comment]
我刚在VPS上追了一下，居然也是无法到达，可是用shadowsocks就可以打开！
root@default:~# traceroute instagram.com
traceroute to instagram.com (107.23.183.195), 30 hops max, 60 byte packets
 1  v33.sioru.com (198.35.46.6)  0.040 ms  0.013 ms  0.011 ms
 2  v213.core1.phx2.he.net (65.19.129.153)  0.096 ms  0.114 ms  0.096 ms
 3  10ge15-3.core1.dal1.he.net (184.105.222.78)  25.368 ms  23.747 ms  29.183 ms
 4  equinix01-dfw3.amazon.com (206.223.118.110)  25.511 ms eqix-da1.a100.1.com (206.223.118.150)  25.828 ms equinix01-dfw3.amazon.com (206.223.118.110)  30.587 ms
 5  54.240.229.92 (54.240.229.92)  60.440 ms 54.240.229.98 (54.240.229.98)  62.452 ms 54.240.229.94 (54.240.229.94)  64.562 ms
 6  54.240.229.0 (54.240.229.0)  68.664 ms 54.240.229.10 (54.240.229.10)  68.995 ms 54.240.229.2 (54.240.229.2)  67.887 ms
 7  54.240.229.172 (54.240.229.172)  68.419 ms 54.240.229.162 (54.240.229.162)  68.437 ms 54.240.229.172 (54.240.229.172)  68.371 ms
 8  54.240.228.179 (54.240.228.179)  67.329 ms  67.898 ms 54.240.228.145 (54.240.228.145)  63.981 ms
 9  72.21.220.6 (72.21.220.6)  68.577 ms 205.251.244.74 (205.251.244.74)  67.596 ms 205.251.244.76 (205.251.244.76)  62.532 ms
10  72.21.220.151 (72.21.220.151)  63.587 ms * 72.21.220.47 (72.21.220.47)  59.643 ms
11  72.21.222.157 (72.21.222.157)  58.430 ms 205.251.245.234 (205.251.245.234)  59.444 ms 72.21.222.155 (72.21.222.155)  64.937 ms
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by lanner2000** [comment]
追了第二次：IP不同，但也是不通！

**Comment by lanner2000** [comment]
root@default:~# traceroute instagram.com
traceroute to instagram.com (54.236.151.170), 30 hops max, 60 byte packets
 1  v33.sioru.com (198.35.46.6)  0.042 ms  0.017 ms  0.018 ms
 2  v213.core1.phx2.he.net (65.19.129.153)  3.922 ms  3.938 ms  3.914 ms
 3  10ge15-3.core1.dal1.he.net (184.105.222.78)  30.837 ms  30.877 ms  30.889 ms
 4  equinix01-dfw3.amazon.com (206.223.118.110)  25.469 ms eqix-da1.a100.1.com (206.223.118.150)  20.365 ms equinix01-dfw3.amazon.com (206.223.118.110)  25.501 ms
 5  54.240.229.98 (54.240.229.98)  68.170 ms 54.240.229.92 (54.240.229.92)  63.862 ms 54.240.229.98 (54.240.229.98)  67.752 ms
 6  54.240.229.12 (54.240.229.12)  63.810 ms 54.240.229.14 (54.240.229.14)  67.704 ms 54.240.229.20 (54.240.229.20)  68.621 ms
 7  72.21.220.10 (72.21.220.10)  63.902 ms 54.240.229.174 (54.240.229.174)  67.806 ms 54.240.229.172 (54.240.229.172)  68.389 ms
 8  54.240.228.151 (54.240.228.151)  63.915 ms 54.240.229.135 (54.240.229.135)  67.229 ms 54.240.228.147 (54.240.228.147)  67.828 ms
 9  72.21.220.20 (72.21.220.20)  68.017 ms 72.21.220.14 (72.21.220.14)  68.073 ms 205.251.244.8 (205.251.244.8)  59.313 ms
10  72.21.220.149 (72.21.220.149)  63.440 ms 72.21.220.133 (72.21.220.133)  65.536 ms 72.21.220.29 (72.21.220.29)  64.281 ms
11  205.251.245.226 (205.251.245.226)  53.174 ms 205.251.245.230 (205.251.245.230)  59.786 ms *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by lanner2000** [comment]
手机移动4G网络VPN连接VPS，可以访问instagram,tracert结果如下：
1. 192.168.99.1; 207.331,  207.216,  207.116
2. 198.35.46.6; v33.sioru.com; 207.023,  206.931,  206.857
3. 65.19.129.153; v213.core1.phx2.he.net; 207.031,  206.956,  217.396
4. 184.105.222.78; 10ge15-3.core1.dal1.he.net; 249.346,  249.269,  249.218
5. 206.223.118.110; equinix01-dfw3.amazon.com; 249.083
5. 206.223.118.150; eqix-da1.a100.1.com; 237.866,  248.792
6. 54.240.229.98; 274.675,  271.340
6. 54.240.229.104; 269.857
7. 54.240.229.16; 269.805
7. 54.239.41.168; 269.745
7. 54.240.229.12; 269.744
8. 54.240.229.166; 269.687,  269.233,  269.464
9. 54.240.228.163; 261.129
9. 54.240.228.151; 264.386
9. 54.240.228.179; 259.767
10. 72.21.220.106; 264.403
10. 205.251.244.4; 251.823
10. 205.251.244.84; 264.109
11. 205.251.245.7; 264.118,  271.806
11. 205.251.245.5; 253.296
12. 205.251.245.250; 271.615
9. 202.97.34.45; 388.221
12. 205.251.245.47; 271.394,  271.258
13. *
14. *
15. *
16. *
17. *
9. 202.97.60.37; 377.810
18. *
19. *
20. *
21. *
22. *
23. *
24. *
25. *
26. *
27. *
28. *
29. *
30. *

**Comment by lanner2000** [comment]
关闭VPN，打开shadowsocks后的追踪结果：
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                             OpenWrt.lan -    0 |   45 |   45 |    0 |    0 |    0 |    0 |
|                            14.155.216.1 -    0 |   45 |   45 |    0 |    2 |    4 |    0 |
|                           113.106.41.37 -    0 |   45 |   45 |    1 |    3 |    7 |    3 |
|                           183.56.66.153 -   24 |   21 |   16 |    3 |   12 |   53 |    4 |
|                             183.56.65.6 -    0 |   45 |   45 |    4 |    6 |   10 |    5 |
|                           202.97.33.214 -    0 |   45 |   45 |    4 |    8 |   12 |    6 |
|                            202.97.60.82 -    0 |   45 |   45 |    5 |    9 |   29 |    9 |
|                           202.97.51.166 -    0 |   44 |   44 |  160 |  162 |  167 |  162 |
|                            202.97.50.82 -    0 |   44 |   44 |  162 |  165 |  169 |  164 |
|      xe-7-3-3.edge2.SanJose3.Level3.net -    0 |   44 |   44 |  157 |  161 |  221 |  158 |
|    ae-4-90.edge1.Washington1.Level3.net -    0 |   44 |   44 |  235 |  239 |  290 |  236 |
|    ae-1-60.edge1.Washington1.Level3.net -    0 |   44 |   44 |  233 |  236 |  289 |  234 |
| AMAZON.COM.edge1.Washington1.Level3.net -    0 |   44 |   44 |  235 |  238 |  275 |  235 |
|                           72.21.220.143 -    0 |   44 |   44 |  246 |  248 |  251 |  250 |
|                           72.21.222.157 -    0 |   44 |   44 |  241 |  250 |  281 |  251 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    8 |    0 |    0 |    0 |    0 |    0 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

**Comment by MuJJus** [comment]
看起来是 VPN 服务器配置不完善，尝试在服务器上执行以下防火墙指令并重拨 VPN 后查看问题是否解决。
```iptables -I FORWARD -i ppp+ -p tcp --syn -j TCPMSS --set-mss 1356```

**Comment by lanner2000** [comment]
谢谢大侠的回复，您的意思是在VPS上运行这条命令是吧！

**Comment by lanner2000** [comment]
我的VPS的配置如下：
root@default:~# ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:636 errors:0 dropped:0 overruns:0 frame:0
          TX packets:636 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:31800 (31.0 KiB)  TX bytes:31800 (31.0 KiB)

ppp0      Link encap:Point-to-Point Protocol
          inet addr:192.168.99.1  P-t-P:192.168.99.9  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1396  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3
          RX bytes:106 (106.0 B)  TX bytes:86 (86.0 B)

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00                                                                             -00
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.                                                                             255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:897985 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1037828 errors:0 dropped:1383 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:554697674 (529.0 MiB)  TX bytes:556038936 (530.2 MiB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00                                                                             -00
          inet addr:104.224.169.***  P-t-P:104.224.169.***  Bcast:104.224.169.***                                                                               Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1

**Comment by lanner2000** [comment]
谢谢，已经搞定！非常感谢！

**Comment by lanner2000** [comment]
看了下mtr，与之前是一样的结果！
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                             OpenWrt.lan -    0 |   30 |   30 |    0 |    0 |    1 |    0 |
|                            192.168.99.1 -    0 |   30 |   30 |  161 |  164 |  169 |  166 |
|                           v33.sioru.com -    0 |   30 |   30 |  162 |  167 |  235 |  167 |
|                  v213.core1.phx2.he.net -    0 |   30 |   30 |  165 |  169 |  175 |  167 |
|              10ge15-3.core1.dal1.he.net -    0 |   30 |   30 |  183 |  186 |  193 |  186 |
|                     eqix-da1.a100.1.com -    0 |   30 |   30 |  182 |  185 |  199 |  188 |
|                          54.240.229.104 -    0 |   30 |   30 |  221 |  224 |  230 |  223 |
|                           54.240.229.20 -    0 |   30 |   30 |  216 |  223 |  230 |  227 |
|                          54.240.229.166 -    0 |   30 |   30 |  217 |  223 |  230 |  227 |
|                          54.240.228.155 -    0 |   30 |   30 |  216 |  224 |  232 |  225 |
|                            72.21.220.18 -    0 |   30 |   30 |  222 |  225 |  229 |  229 |
|                           205.251.245.9 -    0 |   30 |   30 |  217 |  221 |  227 |  220 |
|                         205.251.245.123 -    0 |   30 |   30 |  221 |  224 |  242 |  225 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    5 |    0 |    0 |    0 |    0 |    0 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

**Comment by lanner2000** [comment]
大侠能简单说下原理嘛，真的太神奇啦！

**Comment by MuJJus** [comment]
隧道自动协商出的 MTU 太大，导致数据包无法正常通过，强制锁在一个较小的值即可解决故障。

**Comment by lanner2000** [comment]
谢谢大侠！太感谢了，新年快乐！！！！

**Comment by MuJJus** [comment]
新年快乐
